version: '3.8'  # Docker Compose version

services:
  backend:
    build:
      context: ./backend  # The directory where the backend's Dockerfile is located
    ports:
      - "5000:5000"  # Maps container port 5000 to host port 5000
    env_file:
      - ./backend/.env  # Loads environment variables from backend/.env file
    volumes:
      - ./backend:/app  # Mounts backend folder into the container for live updates
      - /app/node_modules  # Prevents overwriting node_modules inside the container
    restart: unless-stopped  # Ensures backend restarts if it crashes

  frontend:
    build:
      context: ./frontend  # The directory where the frontend's Dockerfile is located
      args:
        - VITE_BACKEND_BASE_URL= http://backend:5000  # Build-time variable (will be set from .env file)
    ports:
      - "3000:80"  # Maps frontend container port 80 (Nginx) to host port 3000
    depends_on:
      - backend  # Ensures backend starts before frontend
    restart: unless-stopped  # Ensures frontend restarts if it crashes
    env_file:
      - ./frontend/.env  # Loads environment variables from frontend/.env file
